using NewsletterSubscribers._Shared.CreateNewsletterSubscriber;

namespace NewsletterSubscribers.Features.CreateNewsletterSubscriber;

public class CreateNewsletterSubscriberCommandValidator : CreateNewsletterSubscriberRequestValidator
{
}